name: Inject API Key and Deploy

on:
  push:
    branches: [main]  # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Inject OpenWeather API Key
      run: |
        sed -i 's/__API_KEY__/${{ secrets.OPENWEATHER_API_KEY }}/g' index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
